### ISSUE TITLE
JS strings crippled...

### ISSUE THREAD

**Issue by janybravo** [jonschlinkert/strip-comments#21]
I've noticed in our JS code becomes crippled after comment stripping:

```javascript
window.amino_cec_callback = function (tag, source, destination, body) {
	debug("///////////// cec_callback ////////////////////");
	debug(tag + " " + source + " " + destination + " " + body);
	debug("///////////// cec_callback ////////////////////");
};
```
becomes following: 

```javascript
window.amino_cec_callback = function (tag, source, destination, body) {
	debug("///////////// cec_callback
	debug(tag + " " + source + " " + destination + " " + body);
	debug("///////////// cec_callback
};
```

**Comment by jonschlinkert** [comment]
are you wanting to strip all comments, or just block or line comments? in any case this looks like a bug. thanks for reporting

**Comment by mjpearson** [comment]
+1 here, i'm attempting to annotate a json file which has structures like so : 

```
"config" : {
          "properties" : {
            "device_id" : {
              "type" : "string",
              "title" : "Device ID",
              "label": {
                "$ref": "/rpcs/device_ids#thermostats/*/{name}"
              },
              "oneOf" : [
                {
                  "$ref": "/rpcs/device_ids#thermostats/*/{device_id}"
                }
              ]
            }
          },
          "required" : [ "device_id" ],
          "disposition" : [ "device_id" ]
        }
```

and parts of the structure are being truncated and invalidated as json (notice the truncated $oneOf attribute) : 
```
       "config" : {
          "properties" : {
            "device_id" : {
              "type" : "string",
              "title" : "Device ID",
              "label": {
                "$ref": "/rpcs/device_ids#thermostats{device_id}"
                }
              ]
            }
          },
          "required" : [ "device_id" ],
          "disposition" : [ "device_id" ]
        }
```

**Comment by tunnckoCore** [comment]
@mjpearson yea, because it almost impossible to do this thing based regex. There have a lot of bugs and edge cases, and not so edge cases. I'm curios why you would to strip comments from json with that package.

Try [acorn-strip-comments](https://github.com/tunnckoCore/acorn-strip-comments) (which i should find time to finish) or [strip-json-comments](https://www.npmjs.com/package/strip-json-comments) which is exactly for these things.

**Comment by mjpearson** [comment]
Thanks @tunnckoCore i'll give those a try.  It's useful to be able to comment out and disable parts of json files as well as annotate and document working configurations (and build [docco](https://jashkenas.github.io/docco) documents for example)

**Comment by tunnckoCore** [comment]
Oh, yea, okey. Btw, PRs and issues are welcome for `acorn-strip-comments`, i've opened one issue for what should be done. :)

**Comment by jonschlinkert** [comment]
sounds like we can close here then?

**Comment by tunnckoCore** [comment]
Maybe, im not sure.
I think it's always better to have it listed, even if there is other 6 opened bug issues. :)

**Comment by jonschlinkert** [comment]
sorry this took so long. I've completely refactored the lib to use real parsing instead of regex. Here are the test cases mentioned in this issue: https://github.com/jonschlinkert/strip-comments/blob/master/test/test.js#L35-L47. 

closing since the issues mentioned here were resolved, please open a new issue if you experience any more problems.
