### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by amnsss** [jonschlinkert/strip-comments#37]
`{...this.passenger}`
`Error: Line 340: Unexpected token ...`

**Comment by jonschlinkert** [comment]
please provide more information

**Comment by amnsss** [comment]
this e6 spread syntax `{...obj}` will be error.
![image](https://cloud.githubusercontent.com/assets/12807953/26569748/282f7a34-453f-11e7-8ee2-a0dddb558118.png)

**Comment by shawnmclean** [comment]
I'm running into this error now. I'm trying to strip comments from an invalid javascript file. babel is throwing a similar error.

Input: 

```
/**
 * @overview Test
 */

function (user, context, callback) {
  callback(null, user, context);
}
```

**Comment by jonschlinkert** [comment]
@shawnmclean can you paste the error message here so we can see what's happening?

**Comment by jonschlinkert** [comment]
That's failing because the javascript is invalid. the function is missing a name. 

Fwiw, before I switched to using babylon for parsing, this library didn't care if you had valid javascript, since it used regex for stripping comments. However, there were occasional issues about edge cases, since there is no way to use regex for this with 100% accuracy. Most of the edge cases had to do with things like code comments in quoted strings, etc. 

Given that there is a tradeoff either way, I'm not necessarily opposed to having a "relaxed" option that uses regex, so that users can strip comments from invalid javascript. Otherwise I'm not sure how what the best solution would be.

**Comment by shawnmclean** [comment]
Is there a way to tell babylon to not validate the js?

If not, this can be reclosed.

**Comment by jonschlinkert** [comment]
> Is there a way to tell babylon to not validate the js?

Options are passed to babylon I think, so if there is an option for that mentioned in the babel or babylon docs, it should work.

**Comment by jonschlinkert** [comment]
This library was refactored and no longer uses babylon. This should no longer be an issue.
